### ISSUE TITLE
Main_Customer

### ISSUE THREAD

**Issue by eunbeek** [Seneca-PlaNA/body-contouring-clinic#155]
- [x] login
- [x] signUp
- [ ] requestEmail => delete and change UI
- [ ] confirmEmail => delete and change UI

**Comment by sonechca** [comment]
Move to mileston4 to make a component with testing

**Comment by eunbeek** [comment]
@sonechca  We will delete email confirmation so please redesign signup process UI

**Comment by eunbeek** [comment]
![image](https://user-images.githubusercontent.com/50673489/115084076-55868000-9ed6-11eb-817e-fe2dfeba4f67.png)

![image](https://user-images.githubusercontent.com/50673489/115084087-5a4b3400-9ed6-11eb-8ce3-ebdbac410d2f.png)

**Comment by yuanLeeMidori** [comment]
and the forget id and forget password UI? we don't have email validation so maybe not these 2 functions?

![image](https://user-images.githubusercontent.com/50813726/115086321-03dff480-9eda-11eb-82ce-a5fdadf09b46.png)
