### ISSUE TITLE
Admin_Request

### ISSUE THREAD

**Issue by eunbeek** [Seneca-PlaNA/body-contouring-clinic#168]
- [x] getRequests (possible duplicate)
- [ ] searchRequest (possible duplicate)
- [x] getRequest (possible duplicate)
- [x] editRequestAnswer
- [x] createRequestAnswer

**Comment by yuanLeeMidori** [comment]
Request collection and UI might need to discuss modify.

1. Where is request answer stored?
2. Where is edit, delete, view answer UI?
3. Display id seems meaningless, should we change it to something else?
![image](https://user-images.githubusercontent.com/50813726/109104193-8e398280-76f9-11eb-8c5d-a45e944edc69.png)
4. Display customer id or customer account userID?
![image](https://user-images.githubusercontent.com/50813726/109104275-b1643200-76f9-11eb-9889-585c59f77ce1.png)

**Comment by eunbeek** [comment]
1. Yes, our db does not thie collectoin, need to fix
2. Admin does not need to have delete, edit one, please remove it on your list
3. I have same concerns,
          1) simply  using " Request "
          2) using index from the parent component

**Comment by yuanLeeMidori** [comment]
1. is fixed by #181
2. removed, I, however, leave edit and delete request answer, we can talk about this
3. first option sounds fair enough

**Comment by yuanLeeMidori** [comment]
Closed by #180, the rest of this issue will be handled by #204
