### ISSUE TITLE
Add another database for uploading files

### ISSUE THREAD

**Issue by yuanLeeMidori** [Seneca-PlaNA/body-contouring-clinic#196]
For example, in request system, user can upload files. But our database is not big enough, need to move it somewhere else.
Download Image
- [x] "/VIP"
- [x] "/Request/Detail/:id"
- [x] "/Request/Admin/Details/602a2e00bb2ab61bb8b37ab3"

Uplaod Image
- [x] "/Request/Create"
- [x]  "/Request/Edit/:id"
- [x] "/VIP/Admin/Manage/Edit/:id"
- [x] "/VIP/Admin/Manage/Create'

**Comment by eunbeek** [comment]
Hi, @sonechca @rko7 @yuanLeeMidori 
This is image server to save all kind of file.
I did not make delete api in this server, so be careful of uploading file. 

API URL : bodycontouringclinicimage.herokuapp.com
API document: 
[bodyContouringClinicImageAPI.postman_collection.zip](https://github.com/Seneca-PlaNA/body-contouring-clinic/files/6194496/bodyContouringClinicImageAPI.postman_collection.zip)
git repository:
https://github.com/Seneca-PlaNA/body-contouring-clinic-image

I will let you know how to use this API soon.
