### ISSUE TITLE
Create/Edit Offer

### ISSUE THREAD

**Issue by rko7** [Seneca-PlaNA/body-contouring-clinic#303]
Page Access
- [x] /VIP/admin page with general user account redirect to VIP admin page, not redirect to log in page

View Offer
- [x] need to fix pagination
    - [x] it need to be maximum 8 offers per pages (10 offers are displayed in one page)
    - [x] it display incorrect amount of page
    - [x] page number button/left/right button doesn't work

Create Offer
- [ ] able to create offer only with title and start-date (no need end-date to create->occurs  'Unhandled Rejection (TypeError): Cannot read property 'split' of undefined' error when you try to edit it )
- [x] able to create offer with start-date after end-date (able to edit)
- [ ] Error message(Validation) does not displayed on empty field

Edit offer
- [ ] Able to save edit with any empty field (Title, content, price, attachment)
- [x] Able to edit offer with start date after end date
- [ ] Error message(Validation) does not displayed on empty field

Upload File
- [ ] when trying to upload txt, pdf, or other invalid file format, it shows upload success message and able to save it but no attach file has uploaded
- Error message(Validation) modal does not display

**Comment by eunbeek** [comment]
#288
