### ISSUE TITLE
Edit Password Validation

### ISSUE THREAD

**Issue by rko7** [Seneca-PlaNA/body-contouring-clinic#353]
- when you edit password and if it is less than 8 characters, it should display error message that says 
- [ ] "password need to be longer than 8 characters"

**Comment by eunbeek** [comment]
is it should be more than 8?

**Comment by rko7** [comment]
Yeah, It was on the register spread sheet page. if it isn't, you cannot login

**Comment by yuanLeeMidori** [comment]
So it should be more than 8? right? can you update your description? Thanks @rko7
