### ISSUE TITLE
non-login user/general customer access to VIP/admin/create, VIP/admin/edit/:id

### ISSUE THREAD

**Issue by rko7** [Seneca-PlaNA/body-contouring-clinic#357]
non-logged in user/general customer can access to :

- [x]  /VIP/Admin/Manage/Create
- [x] /VIP/Admin/Manage/Edit/602aff44375d3c4edd01d99d

however, 
they cannot access to:
/VIP/Admin, /VIP/Admin/Manage -> this redirect to main home page

**Comment by eunbeek** [comment]
I know this bug but it did not appear any button to general user so we need it?

**Comment by rko7** [comment]
Hmm true I'll just delete that row from the excel sheet and close this issue
