### ISSUE TITLE
Create offers

### ISSUE THREAD

**Issue by yuanLeeMidori** [Seneca-PlaNA/body-contouring-clinic#411]
Create about 5 offers with pictures in VIP page.

**Comment by eunbeek** [comment]
Hard to make over 3 offers because the original offers are only 3.

**Comment by eunbeek** [comment]
https://bodycontouringclinic.herokuapp.com/VIP/Admin

**Comment by eunbeek** [comment]
![image](https://user-images.githubusercontent.com/50673489/115098898-add27780-9f00-11eb-89db-2dd6b4a3c90c.png)

**Comment by yuanLeeMidori** [comment]
okay sure! let's do 3.
close it since you've created them
