### ISSUE TITLE
Create schedules and appointments

### ISSUE THREAD

**Issue by yuanLeeMidori** [Seneca-PlaNA/body-contouring-clinic#412]
Create schedules:
- [x] at least one schedule for each weeks in April
- [x] at least one schedule in May
- [x] at least one schedule in June
- [x] sequence of schedules from April 21 to 30

Create appointments:
- [x] at least one in the last week of April
- [x] at least one in May
- [x] at lease one in June

**Comment by eunbeek** [comment]
![image](https://user-images.githubusercontent.com/50673489/115128851-c1d4b280-9fae-11eb-8aa9-a7747805acb3.png)
![image](https://user-images.githubusercontent.com/50673489/115128859-d1ec9200-9fae-11eb-9cb0-1c7f35079e55.png)

**Comment by eunbeek** [comment]
![image](https://user-images.githubusercontent.com/50673489/115128915-34de2900-9faf-11eb-9097-b19e4f97ce9a.png)
![image](https://user-images.githubusercontent.com/50673489/115128981-b635bb80-9faf-11eb-8bc6-d165dd2b7a51.png)
