### ISSUE TITLE
Create requests

### ISSUE THREAD

**Issue by yuanLeeMidori** [Seneca-PlaNA/body-contouring-clinic#413]
Create requests
- [x] at least one in November 2020
- [x] at least one in January 2021
- [x] at least one in February 2021
- [x] at least one in March 2021
- [x] at least one in April 2021

**Comment by eunbeek** [comment]
All Requests
![image](https://user-images.githubusercontent.com/50673489/115100647-ea57a080-9f0b-11eb-966b-959943d87140.png)
