### ISSUE TITLE
Create FAQ

### ISSUE THREAD

**Issue by yuanLeeMidori** [Seneca-PlaNA/body-contouring-clinic#414]
Create at least one FAQ for each category.

**Comment by eunbeek** [comment]
![image](https://user-images.githubusercontent.com/50673489/115100003-bed2b700-9f07-11eb-8563-271d10710a85.png)
![image](https://user-images.githubusercontent.com/50673489/115100005-c4300180-9f07-11eb-8601-d47ce65117ca.png)
![image](https://user-images.githubusercontent.com/50673489/115100010-c8f4b580-9f07-11eb-86cb-47c0000413e4.png)
![image](https://user-images.githubusercontent.com/50673489/115100013-ceea9680-9f07-11eb-99c1-0351e5e04fa9.png)
