### ISSUE TITLE
Disable service dropdown in create appointment by offer

### ISSUE THREAD

**Issue by yuanLeeMidori** [Seneca-PlaNA/body-contouring-clinic#436]
![image](https://user-images.githubusercontent.com/50813726/115319231-507f3600-a14d-11eb-8865-29c993339cfa.png)
The service is fixed in offer, just disable the dropdown.

**Comment by eunbeek** [comment]
![image](https://user-images.githubusercontent.com/50673489/115330682-909ce380-a162-11eb-8956-c678e6cad802.png)

**Comment by eunbeek** [comment]
Sorry, This is another issue
