### ISSUE TITLE
Create Basic directory and Structure based on the current UI

### ISSUE THREAD

**Issue by eunbeek** [Seneca-PlaNA/body-contouring-clinic#9]
## Add new directory : 

              Appointment (current)
              Request (new)
              Service (new)
              Profile (new)

## Description
 - Create a branch for issue and checkout
 - Create a directory for each part and save your file
 - Make a GitHub issue for each task for PR
 
## Tasks:

 - [x] Appointment structure
 - [x] Request structure
 - [x] Customer structure
 - [x] Register

**Comment by yuanLeeMidori** [comment]
@eunbeek  I believe this one has completed?

**Comment by eunbeek** [comment]
@yuanLeeMidori This pr is for the directory structure, not UI, and I think I am done for Request one.
